name: akebi2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^4.0.7
  firebase_core: ^2.27.0
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  http: ^1.4.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ashita_icon.png
    - assets/user_icon.png
