// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbh4DNYa3ClAv26M_Y8QfdOjBaIymFjy0',
    appId: '1:426459776030:web:4215b7523547d364689a0f',
    messagingSenderId: '426459776030',
    projectId: 'chatapp-359ec',
    authDomain: 'chatapp-359ec.firebaseapp.com',
    storageBucket: 'chatapp-359ec.firebasestorage.app',
    measurementId: 'G-T65B7H93SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8e0jkYoo9-IljFRiBga9csm33DPlmbUM',
    appId: '1:426459776030:android:b7ee2590d9bcc82e689a0f',
    messagingSenderId: '426459776030',
    projectId: 'chatapp-359ec',
    storageBucket: 'chatapp-359ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCue1uggM1-sAaw2br70GAyJfm-L3Y3lAk',
    appId: '1:426459776030:ios:06493e1b8f7809fc689a0f',
    messagingSenderId: '426459776030',
    projectId: 'chatapp-359ec',
    storageBucket: 'chatapp-359ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCue1uggM1-sAaw2br70GAyJfm-L3Y3lAk',
    appId: '1:426459776030:ios:06493e1b8f7809fc689a0f',
    messagingSenderId: '426459776030',
    projectId: 'chatapp-359ec',
    storageBucket: 'chatapp-359ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbh4DNYa3ClAv26M_Y8QfdOjBaIymFjy0',
    appId: '1:426459776030:web:7c9ed30605fa61fb689a0f',
    messagingSenderId: '426459776030',
    projectId: 'chatapp-359ec',
    authDomain: 'chatapp-359ec.firebaseapp.com',
    storageBucket: 'chatapp-359ec.firebasestorage.app',
    measurementId: 'G-Q2BZTKJZXJ',
  );
}
